apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: lightspeed-stack-metrics
  namespace: rolling-demo-ns
spec:
  namespaceSelector:
    matchNames:
      - rolling-demo-ns
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
      app.kubernetes.io/instance: rolling-demo
  podMetricsEndpoints:
    - port: lcs-backend
      path: /metrics
      interval: 30s
      scheme: HTTP
