apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdhai-rhdh-dev-monitoring
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/thepetk/rosa-gitops.git
    targetRevision: dev
    path: devcluster-observability/apps/monitoring/base/rhdhai-rhdh-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdhai-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
