kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  app-config-rhdh.yaml: |
    app:
      title: AI Dev Developer Hub
      baseUrl: "${RHDH_BASE_URL}"
    auth:
      environment: production
      session:
        secret: "${BACKEND_SECRET}"
      providers:
        github:
          production:
            clientId: "${CLIENT_ID}"
            clientSecret: "${CLIENT_SECRET}"
        oidc:
          production:
            metadataUrl: "${KEYCLOAK_METADATA_URL}"
            clientId: "${KEYCLOAK_CLIENT_ID}"
            clientSecret: "${KEYCLOAK_CLIENT_SECRET}"
            callbackUrl: "${RHDH_CALLBACK_URL}"
            prompt: auto
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
    backend:
      auth:
        externalAccess:
          - type: static
            options:
              token: ${ADMIN_TOKEN}
              subject: admin-curl-access
        keys:
          - secret: "${BACKEND_SECRET}"
      baseUrl: "${RHDH_BASE_URL}"
      cors:
        origin: "${RHDH_BASE_URL}"
      csp:
        upgrade-insecure-requests: false
        img-src:
          - "'self'"
          - "data:"
          - https://img.freepik.com
          - https://cdn.dribbble.com
    signInPage: oidc
    catalog:
      providers:
        keycloakOrg:
          default:
            baseUrl: "${KEYCLOAK_BASE_URL}"
            loginRealm: "${KEYCLOAK_REALM}"
            realm: "${KEYCLOAK_REALM}"
            clientId: "${KEYCLOAK_CLIENT_ID}"
            clientSecret: "${KEYCLOAK_CLIENT_SECRET}"
            schedule:
              frequency: { minutes: 1 }
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail
      rules:
          - allow: [Component, Group, User, Resource, Location, Template, API]
      locations:
        - type: url
          target: https://github.com/redhat-ai-dev/ai-lab-template/blob/main/all.yaml
          rules:
            - allow: [Location, Template]
    lightspeed:
      servers:
      - id: team_cluster
        url: "${OLLAMA_URL}"
        token: "${OLLAMA_TOKEN}"
        type: "openai"
    permission:
      enabled: true
      rbac:
        policies-csv-file: ./rbac-policy.csv
        policyFileReload: true
        admin:
          users:
            - name: user:default/jcollier
