apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: dev-backstage-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          resources: {}
          image: quay.io/tpetkos/backstage:1.40.2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: backstage-secrets
            - secretRef:
                name: keycloak-secrets
            - secretRef:
                name: github-secrets
          volumeMounts:
            - name: app-config
              mountPath: /app/config
            - name: dynamic-plugins-config
              mountPath: /app/plugins
          readinessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
          livenessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
      volumes:
        - name: app-config
          configMap:
            name: backstage-app-config
        - name: dynamic-plugins-config
          configMap:
            name: backstage-dynamic-plugins
