apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-hub
  namespace: dev-backstage-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer-hub
  template:
    metadata:
      labels:
        app: developer-hub
    spec:
      containers:
        - name: backstage
          resources: {}
          image: quay.io/rhdh/rhdh-hub-rhel9:1.8
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: kubernetes-secrets
            - secretRef:
                name: github-secrets
            - secretRef:
                name: rhdh-secrets
            - secretRef:
                name: argocd-secrets
            - secretRef:
                name: lightspeed-secrets
          volumeMounts:
            - name: app-config
              mountPath: /app/config
            - name: dynamic-plugins-config
              mountPath: /app/plugins
          readinessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
          livenessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
        - name: road-core-sidecar
          resources: {}
          env:
            - name: PROJECT
              value: rhdh
            - name: RCS_CONFIG_FILE
              value: /app-root/config/rcsconfig.yaml
            - name: RHDH_CONFIG_FILE
              value: /app-root/config/app-config-rhdh.yaml
          envFrom:
            - secretRef:
                name: team-cluster-key
            - secretRef:
                name: secrets-rhdh
          image: 'quay.io/redhat-ai-dev/road-core-service:latest'
          ports:
            - containerPort: 8080
              name: rcs-backend
              protocol: TCP
          volumeMounts:
            - mountPath: /app-root/config/rcsconfig.yaml
              name: rcsconfig
              subPath: rcsconfig.yaml
            - mountPath: /app-root/config/team-cluster-key/team_cluster_key.txt
              name: openai
              subPath: team_cluster_key.txt
            - mountPath: /app-root/config/app-config-rhdh.yaml
              name: app-config-rhdh
              subPath: app-config-rhdh.yaml
      volumes:
        - name: app-config
          configMap:
            name: app-config-rhdh
        - name: dynamic-plugins-config
          configMap:
            name: dynamic-plugins-rhdh
