apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backstage.yaml
  - app-config.yaml
  - dynamic-plugins.yaml
  - rcsconfig.yaml
  - rbac.yaml

namespace: dev-backstage-mcp
